# Generated by Django 4.2.4 on 2024-11-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserListing',
        ),
    ]
