# Generated by Django 4.2.4 on 2024-02-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
