# Generated by Django 4.2.4 on 2024-11-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0002_delete_userlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Mutare', 'Mutare'), ('Kwekwe', 'Kwekwe'), ('Gweru', 'Gweru'), ('Kadoma', 'Kadoma'), ('Victoria Falls', 'Victoria Falls'), ('Masvingo', 'Masvingo'), ('Kariba', 'Kariba'), ('Karoi', 'Karoi'), ('Chinhoyi', 'Chinhoyi'), ('Marondera', 'Marondera'), ('Chegutu', 'Chegutu'), ('Chitungwiza', 'Chitungwiza'), ('Norton', 'Norton')], max_length=100),
        ),
    ]
