# Generated by Django 4.2.4 on 2024-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0002_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
