# Generated by Django 4.2.4 on 2024-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0003_alter_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Enter your description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.PositiveIntegerField(help_text='Size in square metres'),
        ),
    ]
