# Generated by Django 4.2.4 on 2024-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0003_profile_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
