# Generated by Django 4.2.4 on 2024-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0004_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
