# Generated by Django 4.2.4 on 2024-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0005_product_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
