# Generated by Django 4.2.4 on 2024-11-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0005_alter_listing_size_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
