# Generated by Django 4.2.4 on 2024-03-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
