# Generated by Django 4.2.4 on 2024-11-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
