# Generated by Django 4.2.4 on 2024-03-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0010_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Body',
            new_name='body',
        ),
    ]
