# Generated by Django 4.2.4 on 2024-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0012_rename_date_message_time_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
