# Generated by Django 4.2.4 on 2024-03-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0013_alter_blog_options_profile_followed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
