# Generated by Django 4.2.4 on 2024-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0014_remove_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follower_name',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
