# Generated by Django 4.2.4 on 2025-03-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0018_post_liked_post_no_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
