# Generated by Django 4.2.4 on 2025-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maricho', '0019_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
