from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('ajax', views.ajax, name='ajax'),
    path('blog-details/<int:blog_id>/<str:blog_title>', views.blog_details, name='blog-details'),
    path('blog_create', views.blog_create, name='blog_create'),
    path('job-details/<int:job_id>', views.job_details, name='job-details'),
    path('company-list', views.company_list, name='company-list'),
    path('property-list', views.property_list, name='property-list'),
    path('create-list', views.create_listing, name='create-list'),
    path('listing-detail/<int:listing_id>', views.listing_detail, name='listing-detail'),
    path('ratings/<int:listing_id>/', views.listing_ratings, name='listing-ratings'),
    path('add_rating/<int:listing_id>/', views.add_rating, name='add_rating'),
    path('job-list/', views.job_list, name='job-list'),
    path('job-cat/', views.job_cat, name='job-cat'),
    path('job-land/', views.job_land, name='job-land'),
    path('chat/<int:profile_id>', views.chat , name='chat'),
    path('<int:year>/<int:month>/<int:day>/<slug:post/', views.post_detail, name='post_detail'),
    path('signup', views.signup, name='signup'),
    path('job', views.job_post, name='job'),
    path('like-post', views.like_post, name='like-post'),
    path('follow-profile', views.follow_profile, name='follow-profile'),
    path('signin', views.signin, name='signin'),
    path('product', views.product_view, name='product'),
    path('product-details/<int:product_id>/<str:product_name>', views.product_detail, name='product-details'),
    path('home', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('chat', views.send_message, name='chat'),
    path('settings', views.settings, name='settings'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('company_profile/<int:company_id>', views.company_profile, name='company_profile'),
    path('jobseeker_profile/<int:profile_id>', views.jobseeker_profile, name='jobseeker_profile'),
    path('property_profile/<int:property_id>', views.property_profile, name='property_profile'),
    path('profile-update', views.profile_update, name='profile-update'),
    path('post', views.post_create, name='post'),
    path('post/<slug:slug>/edit/', views.edit_post, name='edit_post'),
    path('comment/<int:post_id>', views.comment_view, name='comment'),
    path('load_comment/<int:post_id>', views.load_comments, name='load_comment'),
    path('category/', views.categories, name='category'),
    path('comment-details/<int:post_id>/<slug:slug>', views.comment_details, name='comment_details'),
    path('leads/', views.lead_list, name='lead_list'),
    path('leads/create/', views.lead_create, name='lead_create'),
    path('tasks', views.task_list, name='task_list'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('create/', views.create_invoice, name='create_invoice'),
    path('add_items/<int:invoice_id>/', views.add_items, name='add_items'),
    path('invoice_detail/<int:invoice_id>/', views.invoice_detail, name='invoice_detail'),
    path('customers/create/', views.create_customer, name='create_customer'),
    path('customers/edit/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('customers/', views.customer_list, name='customer_list'),
    path('news/', views.n_post_list, name='news'),
    path('news/<str:category_name>/', views.news_category, name='post_list_by_category'),
    path('news/<str:category_name>/post/<int:pk>/<str:news_title>', views.n_post_detail_c, name='n_post_detail_c'),
    path('news/post/<int:pk>/<str:news_title>', views.n_post_detail, name='n_post_detail'),
    path('business', views.maricho_business, name='business'),
    path('finance', views.finance, name='finance'),
    path('ai', views.ai, name='ai'),
    path('graphic-design', views.graphic_design, name='graphic_design'),
    path('company-reg', views.company_reg, name='company_reg'),
    path('ads/', views.get_relevant_ads, name='relevant_ads'),
    path('ads/dashboard/', views.dashboard, name='dashboard'),
    path('ads/track_click/<int:ad_id>/', views.track_ad_click, name='track_ad_click'),
    path('web-dev', views.web_dev, name='web_dev'),
    path('<int:recipient_id>/', views.chat, name="chat"),
    path('choice', views.choice, name="choice"),
    path('company', views.company, name="company"),
    path('jobseeker/', views.job_seeker, name="jobseeker"),
    path('property/', views.property, name="property"),
    path('create-page/', views.create_page, name='create_page'),
    path('editor/<slug:slug>/', views.page_editor, name='page_editor'),
    path('save-page/', views.save_page, name='save_page'),
    path('page/<slug:slug>/', views.render_page, name='render_page'),
    path('upload/', views.video_upload, name='video_upload'),
    path('video/<int:video_id>/', views.video_detail, name='video_details'),
    path('video/<int:video_id>/like/', views.toggle_like, name='toggle_like'),
    path('video/<int:video_id>/comment/', views.add_comment, name='add_comment'),
    path('video/<int:video_id>/comments/', views.fetch_comments, name='fetch_comments'),
    # Password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]
# URL for video upload
    # URL for viewing all videos
